### ISSUE TITLE
"event loop is closed" error

### ISSUE THREAD

**Issue by Mr0Null** [yunstanford/pytest-sanic#14]
I have created a fixture for test_server and used it in my tests, but the server is not responding (the server is started and listening)!

On the other hand, If I want to use the test_client, I get "event loop closed" error for my redis pool (the first test is passed, other tests are failed due to this error!).

here is my test:
```
async def test_get_token_post_request(sanic_server):
    """
    POST request
    """
    assert sanic_server.has_started()
    host = sanic_server.host
    port = sanic_server.port
    auth_url = "http://{}:{}/api/v1/auth".format(host, port)
    print(host, port)
    resp = requests.post(auth_url)
    print(resp)
    assert resp.status == 200
    resp_json = resp.json()
    assert resp_json['status'] == 'success'
```

conftest:
```
import pytest
from beepaste import app
from sanic.websocket import WebSocketProtocol

@pytest.yield_fixture
def app_srv():
    yield app

@pytest.fixture
def test_cli(loop, app_srv, test_client):
    return loop.run_until_complete(test_client(app_srv, protocol=WebSocketProtocol))

@pytest.fixture
def sanic_server(loop, app_srv, test_server):
    return loop.run_until_complete(test_server(app_srv))

```

and you can find the project here: https://gitlab.com/beeit/beepaste/beepaste-backend/ (test are not commited!)

**Comment by yunstanford** [comment]
Several gotchas from your posted code:

1. Why are you using request.post against  websocket protocol?
2. You can use the asynchronous test_client instead the sync request. That's designed for this, although it doesn't really matter.
3. Looks like you are testing against global app object directly. It's not a very good practice.

**Comment by Mr0Null** [comment]
I guess you are right (it's my first project and I'm newbie to this thing!)!
However, I managed to solve the issue by defining my own loop fixture without closing loops (now I have committed everything to that repo! that project is open-source 😁 and you can check it.)
btw, I think closing async loops is not a good idea for testing as there might be some tasks waiting to be done.
