### ISSUE TITLE
Headers not passed in test_client

### ISSUE THREAD

**Issue by c-goosen** [yunstanford/pytest-sanic#16]
I hope I am not looking at this wrong, but the TestClient should accept headers in **kwargs. This does not seem to work though.

Context, in my sanic app I am using sanic-jwt tokens so I need to have Authorization headers on protected endpoints.

EX not working:
```
@pytest.fixture
async def test_client_fetch_returns_200(test_client):
    response = await test_client.get('{}/clients/{}'.format(
        API_VERSION,
        CLIENT_ID
    ),
    headers={"Authorization": "Bearer {}".format(ACCESS_TOKEN)})
    )

```
Ex works:
```
@pytest.fixture
async def test_client_fetch_returns_200(test_client):
    response = yield aiohttp.request(
        'GET', "http://{}:{}/{}/clients/{}".format(
            test_client.host,
            test_client.port,
            API_VERSION,
           CLIENT_ID
        ), 
       headers={"Authorization": "Bearer {}".format(ACCESS_TOKEN)})
   )

```

Any ideas, am I passing the headers incorrectly to the TestClient?

**Comment by yunstanford** [comment]
Just added a unit test for testing this, https://github.com/yunstanford/pytest-sanic/commit/51ea50f6f4fdc50c5821c100a03de338298e2927

**Comment by c-goosen** [comment]
Thanks. I might have been passing something wrong, so I am looking at it more in depth. 

Will get back to this if I have it figured out, thanks.

**Comment by c-goosen** [comment]
Yeah I think I was looking at this wrong so ignore me. Thanks for the quick feedback and testcase though!
