### ISSUE TITLE
How to do async fixture

### ISSUE THREAD

**Issue by Jeffwhen** [yunstanford/pytest-sanic#18]
Can I use it with `pytest-asyncio`? I got this `different event loop` error.

**Comment by Jeffwhen** [comment]
I use `asyncpg` as db driver. Need a injected connection obj to setup test context and verify side effects.

**Comment by yunstanford** [comment]
Sorry, i still don't see why it requires. i'm not sure which feature you're relying on and it's missing here.

**Comment by Jeffwhen** [comment]
Here's my planned fixture.

```python3
@pytest.yield_fixture
async def conn():
    transaction = _conn.transaction()
    await transaction.start()
    yield _conn
    await transaction.rollback()
```

I expected I can do something like
```python3
async def test_invalid_id(test_cli, conn):
    # do something with conn to setup context
    # ...

    # Test goes here
    await test_cli.post('/api/register', data={})

    # afterward verify info in database
    # meaning 
    # do something async with conn again
```

This might be naive. But I think it's doable with async fixture support.

**Comment by yunstanford** [comment]
ok, you can do that sth like
```
@pytest.fixture
async def conn(loop):
    transaction = _conn.transaction()
    loop.run_until_complete(transaction.start())
    yield _conn
    loop.run_until_complete(transaction.rollback())
```
And, pytest has deprecated `yield_fixture`, you can just use `@pytest.fixture`.

We could also support `async fixture`.

**Comment by yunstanford** [comment]
pushed a patch for this.
