### ISSUE TITLE
`test_client` fixture clashes with pytest-aiohttp

### ISSUE THREAD

**Issue by burnpanck** [yunstanford/pytest-sanic#22]
If both pytest-sanic and pytest-aiohttp are installed, tests may pick up the wrong fixture. While this clearly is a design problem of pytest's magic fixture identification by name itself (https://github.com/pytest-dev/pytest/issues/3966, https://github.com/pytest-dev/pytest/issues/3834), pytest-sanic could help here by choosing a different name.

**Comment by yunstanford** [comment]
@burnpanck yeah, sure, we can change the fixture name if needed, but it doesn't fix the issue essentially.

Also, is there any reason you wanna install both `pytest-sanic` and `pytest-aiohttp` into one virtualenv ?

**Comment by yunstanford** [comment]
Hey, we can start add a new fixture with a different name, and start to deprecate test_client

**Comment by kataev** [comment]
Hello, when new version with new fixture client name will be released?
Without it, i must copy-paste test_client fixture with another name in my code, i think this it not a good solution.

**Comment by yunstanford** [comment]
Addressed in `1.0.0`
