### ISSUE TITLE
Bug on websockets

### ISSUE THREAD

**Issue by lnmds** [yunstanford/pytest-sanic#26]
I've been having trouble trying to test websockets with pytest-sanic. I don't know if it is something around my app initialization or an actual bug in pytest-sanic.

I've been getting the same issues with Python 3.6 and 3.7, both installs were with sanic 18.12.0, pytest 4.1.1 and pytest-sanic 0.1.15 (which I believe is latest versions for all three).

The traceback is as follows (with some information trimmed out):
```
protocol: <sanic.server.HttpProtocol object at 0x7ff734c2adb0>
transport: <TCPTransport closed=False reading=False 0x55c52293df98>

Traceback (most recent call last):
[...]
  File "[...]/site-packages/sanic/app.py", line 397, in websocket_handler
    ws = await protocol.websocket_handshake(request, subprotocols)
AttributeError: 'HttpProtocol' object has no attribute 'websocket_handshake'

[2019-01-14 02:48:48 -0300] - (sanic.access)[INFO][127.0.0.1:59100]: GET http://127.0.0.1:37291/ws  500 144
```

If need be, here follows the server and test code:
```py
import sanic

app = sanic.Sanic()

@app.websocket('/ws')
async def test_ws(request, websocket):
    await websocket.send('test message')
    await websocket.close()

if __name__ == '__main__':
    app.run()
```

Test:
```python
import pytest
from run import app as origapp

@pytest.fixture
def app():
    return origapp

@pytest.fixture
def test_cli(loop, app, test_client):
    return loop.run_until_complete(test_client(app))

async def test_ws(test_cli):
    ws = await test_cli.ws_connect('/ws')
    d = await ws.receive()
    assert d
```

**Comment by yunstanford** [comment]
Hey, you can find example in README or documentation https://pytest-sanic.readthedocs.io/en/latest/,

```
@pytest.fixture
def test_cli(loop, app, test_client):
    return loop.run_until_complete(test_client(app, protocol=WebSocketProtocol))
```

**Comment by lnmds** [comment]
Oh! That wasn't easy to notice as there's the long `app` fixture, made me scroll right through. It would be nice to add a notice (maybe at the Tips section, since there's already two related to websockets) so that users make sure `protocol` is set before anything else.

It works now anyways, not a bug, closing.
