### ISSUE TITLE
Test fixtures with scope set to session

### ISSUE THREAD

**Issue by shinybrar** [yunstanford/pytest-sanic#27]
I am using `pytest-sanic` to test my `sanic` application, which communicates with a database layer running in a docker container and I am having difficulty achieving the following test setup:

#### Expected Setup
  1. Spawn one database container for the entire test suite
  2. Setup the database and tables inside the container required by the app
  3. `yield` a session scoped fixture to the app
  4. Run tests
  5. Perform teardown.

#### Sample Code
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Configuration for testing fixtures
"""
try:
    import pytest
    import docker
    from app import app as test_app
    from utilities.database_setup import create_databases, create_tables
except Exception as e:
    raise e

@pytest.yield_fixture
def app():
    yield test_app

@pytest.fixture
def test_cli(loop, app, test_client):
    return loop.run_until_complete(test_client(app))

@pytest.fixture(scope="session", autouse=True)
async def database_setup():
    """ Setup DB Layer for the App """
    print('Setting up pytest session!')
    client = docker.from_env()
    assert client.ping() is True, "Unable to connect to docker."
    print('spawning db container...')
    container = client.containers.run(
        image='redis:latest',
        ports={6380:  6380},
        detach=True
    )
    print('db container running...')
    print('Container ID: {}'.format(container.id))
    db_host = "localhost"
    db_port =  6380
    print('setting up databases...')
    await create_databases(db_host, db_port)
    print('setting up tables...')
    await create_tables(db_host, db_port)
    yield
    print("stopping db container")
    container.kill()
```

#### Error
```
ScopeMismatch: 
You tried to access the 'function' scoped fixture 'loop' with a 'session' scoped request object, involved factories
```

#### Alternatives
I am also open to using other alternatives to achieve this test setup since I am not tied to this approach. 

Any help or suggestions will be greatly appreciated.

**Comment by omarryhan** [comment]
How about doing it this way?

```
async def database_setup(app, loop):
    """ Setup DB Layer for the App """
    print('Setting up pytest session!')
    client = docker.from_env()
    assert client.ping() is True, "Unable to connect to docker."
    print('spawning db container...')
    container = client.containers.run(
        image='redis:latest',
        ports={6380:  6380},
        detach=True
    )
    print('db container running...')
    print('Container ID: {}'.format(container.id))
    db_host = "localhost"
    db_port =  6380
    print('setting up databases...')
    await create_databases(db_host, db_port)
    print('setting up tables...')
    await create_tables(db_host, db_port)
    app.db_container = container

def database_teardow(app, loop):
    app.db_container.kill()

@pytest.yield_fixture
def app():
    app.register_listener(database_setup, 'before_server_start')
    app.register_listener(database_teardown, 'after_server_stop')
    yield test_app
    
```

**Comment by shinybrar** [comment]
@omarryhan I tried the approach you mentioned above, but I run into the following issue:

  - The `@pytest.yield_fixture` `yields` a separate/unique `test_app` for each test
  - `test_app.register_listener(database_setup, 'before_server_start')` starts a container for each `test_app`, but only one container will be spawned because all subsequent initializations won't be able to bind to the already allocated port.

**Comment by omarryhan** [comment]
Ohh gotcha. I think it'd be nice if we can choose our app's scope before running the tests. Maybe, have a --sanic-scope=session command line argument?

Some more ideas:

1. Have a global called db_container that you assign to once if its None. (Or maybe just store the previous container ID)

2. If you don't need to have access to your container you can have a script run your pytests. In this script you can do your db_container logic only once.

**Comment by jackey8616** [comment]
I'm not sure this would help you or not.
Long days ago I faced same issue as you.
I want to make the test running under just one instance, so I use `module` scope.
And the solution I found is to make everything be `module` scope.

Here is my [conftest.py](https://github.com/YunOSC/PyFun-Backend/blob/master/tests/conftest.py) check it out.
```python
import pytest
import asyncio
from pytest_sanic.utils import TestClient

from sanic import Sanic
from app import index
from stage import add_route as stage_add_route


@pytest.yield_fixture(scope='module')
def app():
    app = Sanic()
    app.add_route(index, '/', methods=['GET'])
    stage_add_route(app)
    yield app


@pytest.fixture(scope='module')
def loop():
    # Reference from pytest_sanic.plugin#loop to give a new scope.
    loop = asyncio.get_event_loop()
    yield loop


@pytest.fixture(scope='module')
def test_client(loop):
    # Reference from pytest_sanic.plugin#test_client to give a new scope.
    clients = []

    async def create_client(app, **kwargs):
        client = TestClient(app, loop=loop, **kwargs)
        await client.start_server()
        clients.append(client)
        return client

    yield create_client

    if clients:
        for client in clients:
            loop.run_until_complete(client.close())


@pytest.fixture(scope='module')
def test_cli(loop, app, test_client):
yield loop.run_until_complete(test_client(app))
```

Also, since `test_client` is deprecated,
so just change to `sanic_client` and do the same thing.

Regards.

**Comment by shinybrar** [comment]
I fixed the issue, by starting the database + app configurations through `docker-compose`.
