### ISSUE TITLE
Is there any way to run sanic_client as debug=True?

### ISSUE THREAD

**Issue by sunghyun-lee** [yunstanford/pytest-sanic#28]
Hello!

I have faced problems to test sanic client, which I can't see the traceback on unexpected error.
As far I have found, Sanic does not provide detailed error log (like exception traceback) if not running on debug mode.

So I tried to run `sanic_client` as debug mode but no chance.

I was running sanic server like this way:
```python
@pytest.fixture
def sanic_app():
    app = Sanic()
    return app

def test_something(sanic_app):
    test_cli = sanic_app.test_client

    response = test_cli.get("/api/v1/somewhere/", debug=True, gather_request=True ... )  # this part!
```

With `pytest-sanic`, how can I get `sanic_client` on debug mode? Thanks in advance!

**Comment by jackey8616** [comment]
I think you mean running `pytest` and shows the traceback that Sanic throws out?
Maybe it's nothing to do with `pytest-sanic`.
Try running your pytest command with `--capture=no` argument?
ex: `python -m pytest ./tests --capture=no`.

**Comment by sunghyun-lee** [comment]
@jackey8616 Thanks! Im gonna try it when i can, and gonna close this issue.

**Comment by sunghyun-lee** [comment]
@jackey8616 My bad.

I thought it does not work with `--capture=no` argument.
I tried to reproduce the situation with simple code, but `pytest-sanic` prints out stacktrace.

I think my internal configuration got something blocking to print stacktrace. Sorry for not related issue. Gonna close.

I tested with this code:

```python
import pytest
from sanic import Sanic

app = Sanic()


class TestSanic:
    @pytest.fixture
    def sanic_app(self):
        app = Sanic(__name__)

        @app.route("/")
        async def simple_api(request):
            a = 3 / 0  # should raise ZeroDivisionError

            return a

        yield app

    @pytest.fixture
    def test_cli(self, loop, sanic_app, sanic_client):
        return loop.run_until_complete(sanic_client(sanic_app))

    def test_debug(self, sanic_app):
        request, response = sanic_app.test_client.get('/', debug=True)

        assert response.status == 200  # Test will fail with stacktrace

    async def test_debug_pytest_sanic(self, test_cli):
        response = await test_cli.get('/')

        assert response.status_code == 200  # Test will fail without stacktrace - this prints stacktrace!
```
