### ISSUE TITLE
`tests` dir in project root gets exposed as a package

### ISSUE THREAD

**Issue by igozali** [yunstanford/pytest-sanic#34]
**Steps to Reproduce**

Run the following bash commands:
```
python3 -m venv venv
source venv/bin/activate
pip3 install pytest-sanic
python3  # Run the Python interpreter
```

From inside the Python interpreter, I can now import:
```
import tests.test_simple_fixtures
import tests.test_server
```

**Expected behavior**

I shouldn't be able to import the tests from `pytest-sanic` since tests should be internal to the project.

**Details**

The underlying issue is `setup.py` using `find_packages()` and realizing that tests is also a package since it has an `__init__.py`

Here are some possible fixes:
* excluding the tests directory directly from find_packages() ([link]( https://stackoverflow.com/questions/608855/excluding-a-top-level-directory-from-a-setuptools-package))
* using the `src/` layout ([link](https://blog.ionelmc.ro/2014/05/25/python-packaging/)), which [pytest also adopts](https://github.com/pytest-dev/pytest), but involves some changes in `setup.py`

**Comment by yunstanford** [comment]
@igozali thanks for bringing this up, it should be fixed now.
