### ISSUE TITLE
Deprecation warnings about the event loop

### ISSUE THREAD

**Issue by emacsen** [yunstanford/pytest-sanic#36]
When running tests, I get:

/path/to/tumbrell/lib/python3.8/site-packages/pytest_sanic/utils.py:131: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
    await asyncio.gather(*coros, loop=self.loop)

It seems this should be updated.

**Comment by yunstanford** [comment]
will push fix.
