### ISSUE TITLE
Deprecation warning caused by TestClient passing through `loop`

### ISSUE THREAD

**Issue by cubranic** [yunstanford/pytest-sanic#40]
With `pytest-sanic` freshly installed from PyPI (v1.6.0), when I run the example from `sanic`'s [docs](https://sanic.readthedocs.io/en/latest/sanic/testing.html#pytest-sanic) showing the use of `pytest-sanic`, I get the following error:

```
  /usr/local/miniconda3/envs/sanic-test/lib/python3.6/site-packages/pytest_sanic/utils.py:190: DeprecationWarning: passing through `loop` is deprecated.
    scheme=self._scheme)
```
It looks like it's because `TestClient` creates an instance of `TestServer` in line 187, passing through its `_loop` property:
```
        self._server = TestServer(
                    self._app, loop=self._loop,
                    protocol=self._protocol, ssl=self._ssl,
                    scheme=self._scheme)
```
while `TestServer` warns when `loop` is not `None`.

**Comment by yunstanford** [comment]
Good catch, will fix it.
