### ISSUE TITLE
Compatibility with pytest v.6 and higher

### ISSUE THREAD

**Issue by ShamansCoding** [yunstanford/pytest-sanic#44]
Greetings! Is there any active road map to add compatibility with latest pytest version, which major number at the moment is 6?

Poetry can't resolve the current pytest-sanic with the latest pytest:

```Using version ^6.0.1 for pytest

Updating dependencies
Resolving dependencies... (0.5s)

[SolverProblemError]
Because pytest-sanic (1.6.1) depends on pytest (>=5.2,<6.0)
 and no versions of pytest-sanic match >1.6.1,<2.0.0, pytest-sanic (>=1.6.1,<2.0.0) requires pytest (>=5.2,<6.0).
So, because back depends on both pytest-sanic (^1.6.1) and pytest (^6.0.1), version solving failed.
```

**Comment by fabaff** [comment]
This makes also the package from Fedora Package Collection [uninstallable](https://bugzilla.redhat.com/show_bug.cgi?id=1871605).

**Comment by thamenato** [comment]
@ShamansCoding my PR was merged just now. I tested locally and seems to be working now, would you mind giving it a try on new version 1.6.2? Thanks

**Comment by ShamansCoding** [comment]
@thamenato 
I checked my test suites. Everything seems to be working properly. Thank you!
