### ISSUE TITLE
Replacing aiohttp by lightweight async http client

### ISSUE THREAD

**Issue by discort** [yunstanford/pytest-sanic#47]
**Proposal**: replace heavy `aiohttp` package by lightweight async client, for instance:  [httpx](https://github.com/encode/httpx)

**Background**: `aiohttp` includes implementation for client/server while `pytest-sanic` uses only `ClientSession` functionality. As a result `aiohttp` takes more disk space ~4.0M comparing to ~450kB (`httpx`). Also, `aiohttp` has more auxiliary packages.

**Comment by yunstanford** [comment]
Yep, httpx didn't exist when this package was created.
