### ISSUE TITLE
Replacing aiohttp with httpx broke the response API

### ISSUE THREAD

**Issue by artamonovkirill** [yunstanford/pytest-sanic#49]
When switching to pytest-sanic 1.7.0, we get the following errors:
```
resp = await test_app.get("/TEST", headers=headers)
>       assert resp.status == 404
E       AttributeError: 'Response' object has no attribute 'status'
```
and:
```
r = await test_app.post(<params>)
>           resp = await r.json()
E           TypeError: object dict can't be used in 'await' expression
```

* Should this breaking change be mentioned in the release notes somewhere?
* Should the examples in README.md be updated?

**Comment by yunstanford** [comment]
Oops, sorry for the trouble. I'll update examples and also draft release notes. In the meantime, you can pin the version to 1.6.x as workaround fix. Sorry again!

**Comment by BobCashStory** [comment]
@yunstanford when you do an incompatible change you should do a major version,
 it will help us to follow your changes !
I had to refactor all test this morning for this, 2 hours who I agree to do but not forced :)

**Comment by yunstanford** [comment]
Sorry again guys for the trouble. It was a little bit rush on my side when making the change, and not realize it's incompatible change, my fault tho.

For references, releases w/notes can be found here https://github.com/yunstanford/pytest-sanic/releases
