### ISSUE TITLE
Allow later websockets release

### ISSUE THREAD

**Issue by fabaff** [yunstanford/pytest-sanic#55]
`websockets` has a [constrain](https://github.com/yunstanford/pytest-sanic/blob/master/pyproject.toml#L20). The latest `websockets` is 9.1 and this release is fixing a [authentication vulnerability](https://websockets.readthedocs.io/en/stable/changelog.html) which was introduced with 8.0.

**Comment by mikekeda** [comment]
pytest-sanic requires old websockets version
`ERROR: pytest-sanic 1.7.1 has requirement websockets<9.0,>=8.1, but you'll have websockets 9.1 which is incompatible.`

and with new Sanic release 21.6.0 old websockets version doesn't work
```
lib/python3.7/site-packages/sanic/websocket.py", line 22, in <module>
    from websockets.legacy import handshake
ModuleNotFoundError: No module named 'websockets.legacy'
```

**Comment by twerkmeister** [comment]
We need this too at https://github.com/RasaHQ/rasa

**Comment by yunstanford** [comment]
updated. https://github.com/yunstanford/pytest-sanic/releases

**Comment by twerkmeister** [comment]
Thanks a lot @yunstanford!
