### ISSUE TITLE
Websocket version is incompatible with sanic latest release

### ISSUE THREAD

**Issue by Go0dYear** [yunstanford/pytest-sanic#60]
Hi there, 
just started a new Sanic project and went to trouble with testing because of:
```
There are incompatible versions in the resolved dependencies:
  websockets<10.0,>=9.1 (from pytest-sanic==1.8.1->-r requirements.in (line 7))
  websockets>=10.0 (from sanic==21.9.1->-r requirements.in (line 13))
```
I saw that PR is ready, are you gonna merge it soon? :)
Thanks in advance!

**Comment by yunstanford** [comment]
closed by https://github.com/yunstanford/pytest-sanic/pull/59/files
